export const HOMEPAGE_REQUEST_STARTED = 'HOMEPAGE_REQUEST_STARTED';
export const HOMEPAGE_REQUEST_COMPLETED = 'HOMEPAGE_REQUEST_COMPLETED';
export const DEVICE_DATA_VIEWER_LOAD_STARTED = 'DEVICE_DATA_VIEWER_REQUEST_STARTED';
export const DEVICE_DATA_VIEWER_LOAD_COMPLETED = 'DEVICE_DATA_VIEWER_REQUEST_COMPLETED';
export const REQUEST_ERROR = 'REQUEST_ERROR';
